services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    expose:
      - "8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy_token}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-dummy_token}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN:-dummy_token}
      - SAVE_DATASET=${SAVE_DATASET:-False}
    restart: always
