services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://65.109.80.113:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy_token}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-dummy_token}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN:-dummy_token}
      - SAVE_DATASET=${SAVE_DATASET:-False}
